server:
  port: 8222 #服务端口
spring:
  application:
    name: demo-consume #微服务id
  cloud:
    nacos: #nacos注册地址
        discovery:
          server-addr: 106.14.221.171:8848
          username: nacos
          password: nacos
dubbo: #dubbo与nacos的通信配置
  application:
    name: demo-consume-dubbo #provider在Nacos中的应用id
  registry: #Provider与Nacos通信地址，与spring.cloud.nacos地址一致
    address: nacos://106.14.221.171:8848
  scan:
    base-packages: com.zj.dubbo