server:
  port: 8111 #服务端口
spring:
  application:
    name: demo-service #微服务id
  cloud:
    nacos: #nacos注册地址
        discovery:
          server-addr: 106.14.221.171:8848
          username: nacos
          password: nacos
dubbo: #dubbo与nacos的通信配置
  application:
    name: demo-service-dubbo #provider在Nacos中的应用id
  registry: #Provider与Nacos通信地址，与spring.cloud.nacos地址一致
    address: nacos://106.14.221.171:8848
  protocol:
    name: dubbo #通信协议名
    #name: rest
    port: 20880 #配置通信端口，默认为20880
    accesslog: "true" #输出到log4j
    #accesslog:"http://localhost/log/txt" #输出到文件
  scan:
    base-packages: com.zj.dubbo